# Generated by Django 5.0.4 on 2024-07-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidtasks', '0002_rename_is_completed_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
