# Generated by Django 5.0.4 on 2024-08-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidtasks', '0006_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
